openapi: 3.0.0
info:
  title: PokeAPI
  version: 0.1
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: Returns hello world
  /hello:
    get:
      summary: Return JSON greeting with optional name
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Optional name to greet
      responses:
        '200':
          description: Greeting response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

