openapi: 3.0.0
info:
  title: PokeAPI
  version: 0.1
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: Returns hello world

  /hello:
    get:
      summary: Return JSON greeting with optional name
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Optional name to greet
      responses:
        '200':
          description: Greeting response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /create-table:
    get:
      summary: Create a new table in the database
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: Name of the table to create
      responses:
        '200':
          description: Table created successfully
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Missing parameter

  /add-pokemon:
    post:
      summary: Add a new Pokémon to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - type
                - level
              properties:
                name:
                  type: string
                type:
                  type: string
                level:
                  type: integer
      responses:
        '200':
          description: Pokémon added successfully
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Invalid input
